language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.8.* DRF=3.6.*
  - DJANGO=1.10.* DRF=3.7.*
  - DJANGO=1.11.* DRF=3.7.*
install:
  - pip install -q Django==$DJANGO djangorestframework==$DRF
  - pip install coveralls
  - pip install -r rest_auth/tests/requirements.pip
script:
  - coverage run --source=rest_auth setup.py test
after_success:
  - coveralls
before_script:
  - flake8 . --config=flake8
