language: python
python:
  - "2.7"
env:
  - DJANGO=1.7.7
  - DJANGO=1.8
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
  - pip install -r test_requirements.pip
script:
  - coverage run --source=rest_auth setup.py test
after_success:
  - coveralls
before_script:
  - flake8 . --config=flake8
