language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.5.10
  - DJANGO=1.6.7
  - DJANGO=1.7
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls
script:
  - coverage run --source=rest_auth setup.py test
after_success:
  - coveralls
install: "pip install -r test_requirements.pip"
